In [1]:
import numpy as np

# Tạo mảng
a = np.array([1,2,3])

# In mảng
print(a)

# In ra 1 phần tử
element = a[1]
print(element)

[1 2 3]
2


In [5]:
# Tạo mảng 2 chiều
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)

# In một phần tử
element = matrix[1, 2]
print(element)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
